// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName


import { application } from "./application"
import SortableController from "./sortable_controller"




import { eagerLoadControllersFrom } from "@hotwired/stimulus-loading"
eagerLoadControllersFrom("controllers", application)


import ConfirmationController from "./confirmation_controller"

import DragController from "./drag_controller"

import HelloController from "./hello_controller"

import TaskController from "./task_controller"

application.register("sortable", SortableController)
application.register("drag", DragController)
application.register("confirmation", ConfirmationController)
application.register("hello", HelloController)

application.register("task", TaskController)
