pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "sortablejs", to: "https://ga.jspm.io/npm:sortablejs@1.15.0/modular/sortable.esm.js"
pin "controllers/application", to: "controllers/application.js"
pin "controllers/sortable_controller", to: "controllers/sortable_controller.js"
pin "controllers", to: "controllers/index.js"